export const ROUTES = {
  home: '/',
  about: '/about',
  howItWorks: '/how-it-works',
  specialties: '/specialties',
  findDoctor: '/find-a-doctor',
  findDoctorProfile: (id: string) => `/find-a-doctor/${id}` as const,
  faq: '/faq',
  contact: '/contact',
  login: '/login',
  register: '/register',
  registerPatient: '/register/patient',
  registerPractitioner: '/register/practitioner',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  patient: {
    root: '/patient',
    dashboard: '/patient/dashboard',
    appointments: '/patient/appointments',
    appointment: (id: string) => `/patient/appointments/${id}` as const,
    book: (practitionerId: string) => `/patient/appointments/book/${practitionerId}` as const,
    messages: '/patient/messages',
    prescriptions: '/patient/prescriptions',
    profile: '/patient/profile',
    profileMedical: '/patient/profile/medical',
  },
  practitioner: {
    root: '/practitioner',
    dashboard: '/practitioner/dashboard',
    schedule: '/practitioner/schedule',
    appointments: '/practitioner/appointments',
    appointment: (id: string) => `/practitioner/appointments/${id}` as const,
    availability: '/practitioner/availability',
    patients: '/practitioner/patients',
    messages: '/practitioner/messages',
    prescriptions: '/practitioner/prescriptions',
    profile: '/practitioner/profile',
    profileCredentials: '/practitioner/profile/credentials',
  },
} as const;
